server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///D:\Projects\sample-spring-cloud-config\server-native\config-repo