server:
  port: 8888
spring:
  profiles:
    active: vault
  cloud:
    config:
      server:
        vault :
          kvVersion: 2
          authentication: TOKEN
          token: s.3qFWxQGRIYfRYPSidNwhLZMI