server:
  port: 8888
spring:
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT MY_KEY, MY_VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
          order: 1
  datasource:
    url: jdbc:mysql://localhost:3306/environment
    username: root
    password: password
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect